# Generated by Django 4.0.1 on 2022-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(auto_created=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
